export interface Tender {
  id: number;
  title: string;
  description: string;
  dateCreated: Date;
  dateIdeasDue: Date;
  dateCloseVoting: Date;
  budget: number;
  link: string;
}

export const tenderList: Tender[] = [
  {
    id: 1,
    title: "Improvement of Public Transportation Services",
    description: "Funds for improving public transportation services in the city",
    dateCreated: new Date("2021-09-01"),
    dateIdeasDue: new Date("2021-09-30"),
    dateCloseVoting: new Date("2021-10-15"),
    budget: 1000000,
    link: "https://example.com/tender1",
  },
  {
    id: 2,
    title: "Improvement of Healthcare Services",
    description: "Funds for improving healthcare services in the region",
    dateCreated: new Date("2021-09-05"),
    dateIdeasDue: new Date("2021-10-05"),
    dateCloseVoting: new Date("2021-10-20"),
    budget: 500000,
    link: "https://example.com/tender2",
  },
  {
    id: 3,
    title: "Improvement of Education Services",
    description: "Funds for improving education services in the state",
    dateCreated: new Date("2021-09-10"),
    dateIdeasDue: new Date("2021-10-10"),
    dateCloseVoting: new Date("2021-10-25"),
    budget: 750000,
    link: "https://example.com/tender3",
  },
  {
    id: 4,
    title: "Improvement of Waste Management Services",
    description: "Funds for improving waste management services in the city",
    dateCreated: new Date("2021-09-15"),
    dateIdeasDue: new Date("2021-10-15"),
    dateCloseVoting: new Date("2021-10-30"),
    budget: 250000,
    link: "https://example.com/tender4",
  },
  {
    id: 5,
    title: "Improvement of Water Supply Services",
    description: "Funds for improving water supply services in the region",
    dateCreated: new Date("2021-09-20"),
    dateIdeasDue: new Date("2021-10-20"),
    dateCloseVoting: new Date("2021-11-05"),
    budget: 400000,
    link: "https://example.com/tender5",
  },
  {
    id: 6,
    title: "Improvement of Road Infrastructure Services",
    description: "Funds for improving road infrastructure services in the state",
    dateCreated: new Date("2021-09-25"),
    dateIdeasDue: new Date("2021-10-25"),
    dateCloseVoting: new Date("2021-11-10"),
    budget: 600000,
    link: "https://example.com/tender6",
  },
  {
    id: 7,
    title: "Improvement of Public Safety Services",
    description: "Funds for improving public safety services in the city",
    dateCreated: new Date("2021-10-01"),
    dateIdeasDue: new Date("2021-11-01"),
    dateCloseVoting: new Date("2021-11-15"),
    budget: 800000,
    link: "https://example.com/tender7",
  },
  {
    id: 8,
    title: "Improvement of Environmental Services",
    description: "Funds for improving environmental services in the region",
    dateCreated: new Date("2021-10-05"),
    dateIdeasDue: new Date("2021-11-05"),
    dateCloseVoting: new Date("2021-11-20"),
    budget: 350000,
    link: "https://example.com/tender8",
  },
  {
    id: 9,
    title: "Improvement of Housing Services",
    description: "Funds for improving housing services in the state",
    dateCreated: new Date("2021-10-10"),
    dateIdeasDue: new Date("2021-11-10"),
    dateCloseVoting: new Date("2021-11-25"),
    budget: 900000,
    link: "https://example.com/tender9",
  },
  {
    id: 10,
    title: "Improvement of Energy Services",
    description: "Funds for improving energy services in the city",
    dateCreated: new Date("2021-10-15"),
    dateIdeasDue: new Date("2021-11-15"),
    dateCloseVoting: new Date("2021-12-01"),
    budget: 200000,
    link: "https://example.com/tender10",
  },
  {
    id: 11,
    title: "Improvement of Tourism Services",
    description: "Funds for improving tourism services in the region",
    dateCreated: new Date("2021-10-20"),
    dateIdeasDue: new Date("2021-11-20"),
    dateCloseVoting: new Date("2021-12-05"),
    budget: 600000,
    link: "https://example.com/tender11",
  },
  {
    id: 12,
    title: "Improvement of Sports Services",
    description: "Funds for improving sports services in the state",
    dateCreated: new Date("2021-10-25"),
    dateIdeasDue: new Date("2021-11-25"),
    dateCloseVoting: new Date("2021-12-10"),
    budget: 400000,
    link: "https://example.com/tender12",
  },
  {
    id: 13,
    title: "Improvement of Cultural Services",
    description: "Funds for improving cultural services in the city",
    dateCreated: new Date("2021-11-01"),
    dateIdeasDue: new Date("2021-12-01"),
    dateCloseVoting: new Date("2021-12-15"),
    budget: 300000,
    link: "https://example.com/tender13",
  },
  {
    id: 14,
    title: "Improvement of Business Services",
    description: "Funds for improving business services in the region",
    dateCreated: new Date("2021-11-05"),
    dateIdeasDue: new Date("2021-12-05"),
    dateCloseVoting: new Date("2021-12-20"),
    budget: 500000,
    link: "https://example.com/tender14",
  },
  {
    id: 15,
    title: "Improvement of Agriculture Services",
    description: "Funds for improving agriculture services in the state",
    dateCreated: new Date("2021-11-10"),
    dateIdeasDue: new Date("2021-12-10"),
    dateCloseVoting: new Date("2021-12-25"),
    budget: 700000,
    link: "https://example.com/tender15",
  },
  {
    id: 16,
    title: "Improvement of Communication Services",
    description: "Funds for improving communication services in the city",
    dateCreated: new Date("2021-11-15"),
    dateIdeasDue: new Date("2021-12-15"),
    dateCloseVoting: new Date("2022-01-01"),
    budget: 150000,
    link: "https://example.com/tender16",
  },
  {
    id: 17,
    title: "Improvement of Justice Services",
    description: "Funds for improving justice services in the region",
    dateCreated: new Date("2021-11-20"),
    dateIdeasDue: new Date("2021-12-20"),
    dateCloseVoting: new Date("2022-01-05"),
    budget: 450000,
    link: "https://example.com/tender17",
  },
  {
    id: 18,
    title: "Improvement of Immigration Services",
    description: "Funds for improving immigration services in the state",
    dateCreated: new Date("2021-11-25"),
    dateIdeasDue: new Date("2021-12-25"),
    dateCloseVoting: new Date("2022-01-10"),
    budget: 800000,
    link: "https://example.com/tender18",
  },
  {
    id: 19,
    title: "Improvement of Social Services",
    description: "Funds for improving social services in the city",
    dateCreated: new Date("2021-12-01"),
    dateIdeasDue: new Date("2022-01-01"),
    dateCloseVoting: new Date("2022-01-15"),
    budget: 250000,
    link: "https://example.com/tender19",
  },
  {
    id: 20,
    title: "Improvement of Emergency Services",
    description: "Funds for improving emergency services in the region",
    dateCreated: new Date("2021-12-05"),
    dateIdeasDue: new Date("2022-01-05"),
    dateCloseVoting: new Date("2022-01-20"),
    budget: 350000,
    link: "https://example.com/tender20",
  },
];
